name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: workflow-data

      - name: Read data
        run: cat data.txt
