# .github/workflows/workflow-2.yml
name: Workflow 2

on:
  repository_dispatch:
    types: [start-workflow-2]

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Access PR Number
        run: |
          echo "Received PR number from Workflow 1: ${{ github.event.client_payload.pr_number }}"
