name: Auto Merge After PR Review

on:
  pull_request_review:
    types:
      - submitted  # Trigger when a review is submitted (approved, changes requested, etc.)

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip requests

      - name: Auto-merge PR after review
        shell: /usr/bin/bash -e {0}
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}  # Dynamic PR number based on the event
        run: |
          python <<EOF
          import requests
          import os

          PERSONAL_ACCESS_TOKEN = os.environ.get("PERSONAL_ACCESS_TOKEN")
          REPO_OWNER = os.environ.get("REPO_OWNER")
          REPO_NAME = os.environ.get("REPO_NAME")
          PR_NUMBER = os.environ.get("PR_NUMBER")
          BASE_URL = f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}"

          HEADERS = {
             
