name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  use-pr-number:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Download PR number artifact
      uses: actions/download-artifact@v3
      with:
        name: pr-number

    - name: Read PR number from artifact
      run: |
        source pr-number
        echo "The PR number is $PR_NUMBER"
