name: Auto Merge Pull Request

on:
  pull_request_review:
    types: [submitted]  # Trigger when a review is submitted

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Check if PR has all approvals
      uses: peter-evans/enable-pull-request-automerge@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge PR if all approvals are in place
      if: ${{ github.event.pull_request.reviews.approvals == github.event.pull_request.reviews.required_approvals }}
      run: |
        echo "All required approvals have been granted. Merging the pull request..."
        gh pr merge ${{ github.event.pull_request.number }} --merge --auto --squash --admin
