name: Print PR Number

on:
  workflow_run:
    workflows:
      - Workflow 1  # Must match the name of Workflow 1 exactly
    types:
      - completed

jobs:
  print-pr-number:
    runs-on: ubuntu-latest

    steps:
      - name: Extract and Print PR Number
        run: |
          # Ensure pull request information is available
          if [ "${{ github.event.workflow_run.pull_requests }}" == "[]" ]; then
            echo "No pull request information found in the event payload. Exiting."
            exit 1
          fi

          # Extract the PR number from the event payload
          PR_NUMBER=$(echo "${{ toJson(github.event.workflow_run.pull_requests) }}" | jq -r '.[0].number')

          echo "Pull Request Number: $PR_NUMBER"
