name: Java CI

on:
  pull_request_review:
    types:
      - submitted  # Trigger when a review is submitted (approved or changes requested)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Compile Java program
      run: javac Main.java

    - name: Run Java program
      run: java Main
