name: Workflow 1

on:
  pull_request_review:
    types:
      - submitted  
jobs:
  capture-pr-number:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get PR number
        id: pr_number
        run: echo "PR_NUMBER=$(echo $GITHUB_REF | awk -F'/' '{print $3}')" >> $GITHUB_ENV

      - name: Upload PR number as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: pr-number
          path: ./pr-number.txt
        run: |
          echo "$PR_NUMBER" > pr-number.txt
