name: Workflow 1

on:
  pull_request_review:
    types:
      - submitted  # Trigger when a review is submitted (approved or changes requested)

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Generate data
        run: echo "This is data from Workflow 1" > data.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: workflow-data
          path: data.txt




# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Set up JDK 17
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'adopt'
#           java-version: '17'

#       - name: Compile Java program
#         run: javac Main.java

#       - name: Run Java program
#         run: java Main

#       - name: Step in Java CI
#         run: echo "Running JAVA CI"

#       - name: Capture and Output PR Number
#         id: capture-pr
#         run: |
#           echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
#           echo "Captured PR Number: ${{ github.event.pull_request.number }}"
